### ISSUE TITLE
Issue with opening jar file (JSON related)

### ISSUE THREAD

**Issue by LIU-TIANHANG** [nusCS2113-AY1819S1/forum#72]
Good day, I have implement a additional JSON file to read and write from. It works fine with idea. However, when I export to Jar. I get the following message when try to open Jar file (java -jar main.jar):
Oct 24, 2018 12:09:34 PM seedu.address.MainApp init
INFO: =============================[ Initializing AddressBook ]===========================
Oct 24, 2018 12:09:34 PM seedu.address.MainApp initConfig
INFO: Using config file : config.json
Oct 24, 2018 12:09:35 PM seedu.address.MainApp initPrefs
INFO: Using prefs file : preferences.json
Oct 24, 2018 12:09:35 PM seedu.address.MainApp initLoginInfo
INFO: Using Login information file : loginInfoManager.json
Oct 24, 2018 12:09:35 PM seedu.address.commons.util.JsonUtil readJsonFile
INFO: Json file loginInfoManager.json not found
Exception in Application init method
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at java.base/sun.launcher.LauncherHelper$FXHelper.main(Unknown Source)
Caused by: java.lang.RuntimeException: Exception in Application init method
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(Unknown Source)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.NoSuchElementException: No value present
        at java.base/java.util.Optional.get(Unknown Source)
        at seedu.address.storage.logininfo.JsonLoginInfoStorage.readLoginInfo(JsonLoginInfoStorage.java:35)
        at seedu.address.storage.logininfo.JsonLoginInfoStorage.readLoginInfo(JsonLoginInfoStorage.java:27)
        at seedu.address.MainApp.initLoginInfo(MainApp.java:146)
        at seedu.address.MainApp.init(MainApp.java:85)
        ... 3 more
Exception running application seedu.address.MainApp

May I check is there any additional things I need to do before build JAR?
Ps: I follow https://www.youtube.com/watch?v=zf7bFiPOKvc for building jar

**Comment by QzSG** [comment]
@LIU-TIANHANG 

Try using the `shadowJar` task in build.gradle instead
Also, have you checked the relevant folder to see if `loginInfoManager.json` actually has been created relative to the location you ran your jar at?

**Comment by LIU-TIANHANG** [comment]
I tried to use shadowJar and it is the same result.
The json file is not create at the relative location of the Jar. 
So I am thinking is there a place to modify the what should be include when building jar.
Also, the loginInfoManager.json is at the same dir as preferences.json and config.json.

**Comment by Psyf** [comment]
@LIU-TIANHANG I mitigated the problem by making my app write a default file in case it is not present. Can you try that?

**Comment by LIU-TIANHANG** [comment]
> @LIU-TIANHANG I mitigated the problem by making my app write a default file in case it is not present. Can you try that?

Hmm, I can try that. But does is solve the problem of not finding the file? As it overwrite every time because file is not found, it seem to violate the purpose of storage.

**Comment by Psyf** [comment]
Once the file is made, my app always finds the file. If that is the problem, it might be that your storage needs some rework. Unlikely, since you sound like you have a working version when running from IDEA.
